site_name: Notes on Math, Physics & More
site_url: https://boonware.github.io/notes/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 3
  font:
    text: Consolas

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      toc_depth: 3
  - attr_list: {}

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Mathematics:
    - Axiomatic Set Theory:
      - Logic: math/axiomatic_set_theory/logic.md
      - Axiomatic Systems & Proofs: math/axiomatic_set_theory/axiomatic_systems_and_proofs.md
      - Zermelo-Fraenkel Axioms: math/axiomatic_set_theory/zermelo_fraenkel_axioms.md

    - Vector Spaces:
      - Dual Space: math/vector_spaces/dual_space.md
      - Hilbert Space: math/vector_spaces/hilbert_space.md

    - Linear Operators:
      - Representation: math/linear_operators/representation.md
      - Basis Dependence: math/linear_operators/basis_dependence.md

    - Real Analysis:
      - Fundamentals of Calculus: math/real_analysis/fundamentals_of_calculus.md
      - Taylor Series: math/real_analysis/taylor_series.md

    - Complex Analysis:
      - Complex Numbers: math/complex_analysis/complex_numbers.md
      - Differentiation: math/complex_analysis/complex_derivative.md
      - Contour Integration: math/complex_analysis/contour_integration.md
      - Laurent Series: math/complex_analysis/laurent_series.md
      - Residue Theorem: math/complex_analysis/residue_theorem.md
    - Calculus of Variations:
      - Euler-Lagrange Equations: math/calculus_of_variations/euler_lagrange_equations.md
    - Group Theory:
      - Group Actions: math/group_theory/group_actions.md
      - Exercise Solutions (Stone & Goldbart): math/group_theory/stone_goldbart_solutions.md

    - Statistics:
      - Introduction: math/statistics/introduction.md
      - Discrete Probability Distributions: math/statistics/discrete_probability_distributions.md
      - Continuous Probability Distributions: math/statistics/continuous_probability_distributions.md
      - Hypothesis Testing: math/statistics/hypothesis_testing.md
      - Z-Score & Z-Test: math/statistics/z_test.md
      - Student's T-Test: math/statistics/t_test.md
      - Pearson's Chi-Squared Test: math/statistics/chi_squared_test.md
      - Maximum Likelihood Estimation: math/statistics/maximum_likelihood_estimation.md
      - Power Transforms: math/statistics/power_transforms.md
      - Correlation: math/statistics/correlation.md
      - Monte Carlo Method: math/statistics/monte_carlo_method.md

    - Numerical Analysis:
      - Floating-Point: math/numerical_analysis/floating_point.md

    - Green Functions:
      - Introduction: math/greens_functions/intro.md

  - Physics:
    - Special Relativity:
      - Galilean Relativity: physics/special_relativity/galilean_relativity.md
      - Spacetime: physics/special_relativity/spacetime.md
    - Quantum Mechanics:
      - Introduction: physics/quantum_mechanics/introduction.md
      - Postulates of Quantum Mechanics: physics/quantum_mechanics/postulates_of_quantum_mechanics.md
      - Schrodinger Equation: physics/quantum_mechanics/schrodinger_equation.md
  - Quantum Computing:
    - Teleportation: quantum_computation/teleportation.md
    - Quantum Parallelism & Deutsch's Algorithm: quantum_computation/deutschs_algorithm.md
    - Deutsch's Algorithm: quantum_computation/deutschs_algorithm.md
    - Deutsch-Josza Algorithm: quantum_computation/deutsch_josza_algorithm.md

  - Machine Learning:
    - Introduction: machine_learning/introduction.md
    - Linear Regression: machine_learning/linear_regression.md
    - Feature Scaling: machine_learning/feature_scaling.md
    - Logistic Regression: machine_learning/logistic_regression.md
    - Natural Language Processing:
        - TF-IDF: nlp/intro.md
